<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account registration at {sitename}' => 'Kontoregistrierung auf {sitename}',
    'Follow the link below to accept or reject the request:' => 'Folge dem unten stehenden Link um die Anfrage zu akzeptieren oder abzulehnen:',
    'Follow the link below to reset your password:' => 'Folge dem unten stehenden Link um dein Passwort zurückzusetzen:',
    'Follow the link below to signup:' => 'Folge dem unten stehenden Link um dich zu registrieren:',
    'Follow the link below to verify your email:' => 'Folge dem unten stehenden Link um deine E-Mail Adresse zu bestätigen:',
    'Grats, your request for {description} has been accepted. Find your key below:' => 'Glückwunsch, deine Anfrage für {description} wurde akzeptiert. Hier ist dein Key:',
    'Hello' => 'Hallo',
    'Invitation to {sitename}' => 'Einladung auf {sitename} erhalten',
    'Password reset for {sitename}' => 'Passwort für {sitename} zurücksetzen',
    'Request accepted at {sitename}' => 'Anfrage auf {sitename} angenommen',
    'Request canceled at {sitename}' => 'Anfrage auf {sitename} abgebrochen',
    'Request received at {sitename}' => 'Anfrage auf {sitename} erhalten',
    'Request rejected at {sitename}' => 'Anfrage auf {sitename} abgelehnt',
    'Sorry, but your request for {description} has been rejected.' => 'Entschuldige, aber deine Anfrage für {description} wurde abgelehnt.',
    'The request for {description} has been canceled.' => 'Deine Anfrage für {description} wurde abgebrochen.',
    'This link is only valid for 24 hours and can only be used when signing up with your email address.' => 'Dieser Link ist nur 24 Stunden und in Verbindung mit dieser E-Mail-Adresse gültig.',
    'Your friend {username} has invited you to join Fezez.' => 'Dein Freund {username} hat dich zu Fezez eingeladen.',
    '{username} has requested one of your offers:' => '{username} hat eine Anfrage zu einem deiner Angebote geschickt:',
    'An email containing your payment link has been sent to {username}.' => 'Eine E-Mail mit deinem Zahlungslink wurde an {username} gesendet.',
    'Once {seller} confirms receiving your payment you will get your key.' => 'Sobald {seller} deine Zahlung bestätigt wirst du deinen Key bekommen.',
    'Payment Confirmed at {sitename}' => 'Zahlung bestätigt auf {sitename}',
    'Payment Required at {sitename}' => 'Zahlung erforderlich auf {sitename}',
    'Please confirm the payment once received.' => 'Bitte bestätige die Zahlung sobald du sie erhalten hast.',
    'Please pay now using the following link:' => 'Bitte bezahle jetzt über folgenden Link:',
    'Request To Buy at {sitename}' => 'Kaufanfrage auf {sitename}',
    'Verify account registration at {sitename}' => 'Bestätige die Registrierung auf {sitename}',
    'You have requested to buy {description} from {seller}.' => 'Du hast eine Kaufanfrage für {description} an {seller} gestellt.',
    'Your payment for {description} has been confirmed. Find your key below:' => 'Deine Zahlung für {description} wurde bestätigt. Nachfolgend findest du deinen Key:',
    '{username} has requested to buy {description} from you.' => '{username} möchte {description} von dir kaufen.',
];
