<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Follow the link below to accept or reject the request:' => 'Folge dem unten stehenden Link um die Anfrage zu akzeptieren oder abzulehnen:',
    'Follow the link below to reset your password:' => 'Folge dem unten stehenden Link um dein Passwort zurückzusetzen:',
    'Follow the link below to signup:' => 'Folge dem unten stehenden Link um dich zu registrieren:',
    'Follow the link below to verify your email:' => 'Folge dem unten stehenden Link um die Anfrage zu akzeptieren oder abzulehnen:',
    'Grats, your request for {description} has been accepted. Find your key below:' => 'Glückwunsch, deine Anfrage für {description} wurde akzeptiert. Hier ist dein Key:',
    'Hello' => 'Hallo',
    'Sorry, but your request for {description} has been rejected.' => 'Entschuldige, aber deine Anfrage für {description} wurde abgelehnt.',
    'The request for {description} has been canceled.' => 'Deine Anfrage für {description} wurde abgebrochen.',
    'This link is only valid for 24 hours and can only be used when signing up with your email address.' => 'Dieser Link ist nur 24 Stunden gültig und kann nur in Verbindung mit dieser E-Mail-Adresse genutzt werden.',
    'Your friend {username} has invited you to join Fezez.' => 'Dein Freund {username} hat dich zu Fezez eingeladen.',
    '{username} has requested one of your offers:' => '{username} hat eine Anfrage zu einem deiner Angebote geschickt:',
];
